dubbo:
  application:
    name: simple-boot
  protocol:
    name: dubbo
    port: -1
  registry:
    id: zk-registry
    address: zookeeper://81.68.234.21:2181
  config-center:
    address: zookeeper://81.68.234.21:2181
  metadata-report:
    address: zookeeper://81.68.234.21:2181