server:
  port: 18080
  servlet:
    context-path: /admin

dubbo:
  application:
    name: admin-boot
  protocol:
    name: dubbo
    port: -1
  registry:
    id: zk-registry
    address: zookeeper://81.68.234.21:2181
  config-center:
    address: zookeeper://81.68.234.21:2181
  metadata-report:
    address: zookeeper://81.68.234.21:2181


############## Sa-Token 配置 (文档: https://sa-token.cc) ##############
sa-token:
  # token名称 (同时也是cookie名称)
  token-name: satoken
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: 2592000
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  activity-timeout: -1
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: true
  # token风格
  token-style: uuid
  # 是否输出操作日志
  is-log: false
