server:
  port: 28081

spring:
  application:
    name: admin # 服务名称
  cloud:
    nacos:
      server-addr: 192.168.0.102:8848 # Nacos地址

dubbo:
  application:
    name: admin
  registry:
    address: nacos://192.168.0.102:8848

