server:
  port: 28081

spring:
  application:
    name: admin # 服务名称
  cloud:
    nacos:
      server-addr: localhost:8848 # Nacos地址

dubbo:
  application:
    name: admin
  registry:
    address: nacos://localhost:8848

